### PR TITLE
update Readme - python deps

### PR DESCRIPTION
**Pull request by danstoner**

### CODE REVIEW

**Comment by roncanepa** [comment]
Might as well ask here since it's semi-relevant: do you know why it was elected to use pillow-simd versus pillow?  The former needs to be built from source, which I had trouble with on 18.04.  While it might have better performance, I don't think we have enough image volume to justify making the build process more fragile.

**Comment by danstoner** [comment]
There was a time when we were processing millions of images, so 2x performance was deemed worth it.  I don't remember any additional reasons but there might have been others.

Sadly, the relevant commit is one of the few where Nathan didn't write a gripping novella of explanation.

https://github.com/iDigBio/idb-backend/commit/8316236bc760bdf2459f4dec27894173b182d670

**Comment by roncanepa** [comment]
Ahhh, that makes more sense. I was thinking of a trickle versus a mountain of images.  I swapped it out on my local build to streamline things.

**Comment by danstoner** [comment]
Media processing / derivative generation has been turned off long enough that we probably have a backlog of 1 - 5 million media that will need processing once the storage system is ready to receive them.

**Pull request merged**
